import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Inter } from "next/font/google";
import "../globals.css";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  if (session?.user) {
    redirect("/");
  }

  return (
    <main className=" h-screen flex items-center justify-center  bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-gray-400 to-gray-600  ">
      <div className={`${inter.className}`}>{children}</div>
    </main>
  );
}
